---
project_path: "{{ playbook_dir }}"
db_data_path: "{{ playbook_dir }}/pg-data"

db_user: "monitor_user"
db_password: "SuperSigurnaLozinka123!"  
db_name: "monitor_db"
db_host: "monitor-db"
db_port: "5432"

node_env: "production"
